import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { createInitialState, PLACE_01_UPGRADES, PLACE_02_UPGRADES, PLACE_03_UPGRADES } from '../src/v2-game.js';
import { placeMapModel } from '../src/aaa-place-map.js';

test('new game map shows coast active and later Places sequentially locked',()=>{const state=createInitialState();const map=placeMapModel(state);assert.equal(map.length,3);assert.equal(map[0].id,'coast');assert.equal(map[0].active,true);assert.equal(map[0].unlocked,true);assert.equal(map[0].completed,0);assert.equal(map[1].id,'sunset');assert.equal(map[1].active,false);assert.equal(map[1].unlocked,false);assert.equal(map[2].id,'garden');assert.equal(map[2].active,false);assert.equal(map[2].unlocked,false);});
test('completed coast becomes revisitable while sunset is current and garden stays locked',()=>{const state=createInitialState();state.placeUpgrades=PLACE_01_UPGRADES.map(upgrade=>upgrade.id);const map=placeMapModel(state);assert.equal(map[0].complete,true);assert.equal(map[0].unlocked,true);assert.equal(map[0].active,false);assert.equal(map[1].unlocked,true);assert.equal(map[1].active,true);assert.equal(map[2].unlocked,false);});
test('completed Sonnenkai unlocks Dachgarten without changing earlier Place completion',()=>{const state=createInitialState();state.placeUpgrades=[...PLACE_01_UPGRADES.map(upgrade=>upgrade.id),...PLACE_02_UPGRADES.map(upgrade=>upgrade.id)];const map=placeMapModel(state);assert.equal(map[0].complete,true);assert.equal(map[1].complete,true);assert.equal(map[1].active,false);assert.equal(map[2].unlocked,true);assert.equal(map[2].active,true);assert.equal(map[2].completed,0);});
test('map progress reflects all places independently without mutating state',()=>{const state=createInitialState();state.placeUpgrades=[...PLACE_01_UPGRADES.map(upgrade=>upgrade.id),...PLACE_02_UPGRADES.map(upgrade=>upgrade.id),PLACE_03_UPGRADES[0].id,PLACE_03_UPGRADES[1].id];const before=structuredClone(state);const map=placeMapModel(state);assert.equal(map[0].completed,6);assert.equal(map[0].ratio,1);assert.equal(map[1].completed,6);assert.equal(map[1].ratio,1);assert.equal(map[2].completed,2);assert.equal(map[2].ratio,2/6);assert.deepEqual(state,before);});
test('Place visual layer keeps coast sunset and garden identities distinct and honors reduced motion',()=>{const mapCss=fs.readFileSync(new URL('../src/aaa-place-map.css',import.meta.url),'utf8'),gardenCss=fs.readFileSync(new URL('../src/aaa-garden.css',import.meta.url),'utf8');assert.match(mapCss,/\.production-place\.place-coast \.place-command/);assert.match(mapCss,/\.production-place\.place-sunset \.place-command/);assert.match(gardenCss,/\.production-place\.place-garden \.place-map-launch/);assert.match(gardenCss,/\.production-place\.place-garden \.journey-line i/);assert.match(mapCss,/@keyframes placeAmbientDrift/);assert.match(mapCss,/@media\(prefers-reduced-motion:reduce\)/);assert.match(mapCss,/\.production-place \.world-art:after\{animation:none/);assert.match(gardenCss,/@media\(prefers-reduced-motion:reduce\)/);});
test('Places map travel layer gives every destination authored color identity without changing map logic',()=>{const css=fs.readFileSync(new URL('../src/aaa-place-map-travel.css',import.meta.url),'utf8'),index=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');assert.match(index,/aaa-place-map-travel\.css\?v=20260815-travel1/);assert.match(css,/\.place-map-node\[data-map-place="coast"\]/);assert.match(css,/\.place-map-node\[data-map-place="sunset"\]/);assert.match(css,/\.place-map-node\[data-map-place="garden"\]/);assert.match(css,/\.place-map-preview\.place-coast/);assert.match(css,/\.place-map-preview\.place-sunset/);assert.match(css,/\.place-map-preview\.place-garden/);assert.match(css,/@media\(prefers-reduced-motion:reduce\)/);});
test('Place launcher uses an actual map glyph rather than the ambiguous target character',()=>{const source=fs.readFileSync(new URL('../src/aaa-place-map.js',import.meta.url),'utf8');assert.match(source,/const mapIcon='<svg/);assert.match(source,/Places Karte öffnen/);assert.doesNotMatch(source,/⌖/);});