import test from 'node:test';
import assert from 'node:assert/strict';
import { BOARD_SIZE, createInitialState, generateFromSlot, moveOrMerge, canMerge, countRequirement, canFulfillOrder, fulfillOrder, buildNextUpgrade, normalizeState } from '../src/v2-game.js';

test('initial V2 board has two generators and merge-ready pairs',()=>{const s=createInitialState();assert.equal(s.board.length,BOARD_SIZE);assert.equal(s.board.filter(i=>i?.kind==='generator').length,2);assert.equal(s.board.filter(i=>i?.family==='coffee'&&i.level===1).length,2);assert.equal(s.board.filter(i=>i?.family==='bakery'&&i.level===1).length,2);});
test('identical items merge into exactly one next-tier item',()=>{const s=createInitialState(),before=s.board.filter(Boolean).length,r=moveOrMerge(s,9,10);assert.equal(r.changed,true);assert.equal(r.type,'merge');assert.equal(r.item.family,'coffee');assert.equal(r.item.level,2);assert.equal(r.state.board[9],null);assert.equal(r.state.board.filter(Boolean).length,before-1);});
test('invalid merge preserves the board',()=>{const s=createInitialState(),snapshot=structuredClone(s.board),r=moveOrMerge(s,9,16);assert.equal(r.changed,false);assert.equal(r.reason,'not-mergeable');assert.deepEqual(r.state.board,snapshot);});
test('move to empty slot preserves identity',()=>{const s=createInitialState(),id=s.board[9].id,r=moveOrMerge(s,9,8);assert.equal(r.changed,true);assert.equal(r.type,'move');assert.equal(r.state.board[8].id,id);assert.equal(r.state.board[9],null);});
test('generator consumes one energy and spawns base item',()=>{const s=createInitialState(),r=generateFromSlot(s,0);assert.equal(r.changed,true);assert.equal(r.family,'coffee');assert.equal(r.state.energy,s.energy-1);assert.equal(r.state.board[r.spawnedIndex].level,1);});
test('full board blocks generation without energy loss',()=>{const s=createInitialState(),filler=s.board[9];s.board=s.board.map((slot,i)=>slot??{...filler,id:`fill-${i}`});const r=generateFromSlot(s,0);assert.equal(r.changed,false);assert.equal(r.reason,'board-full');assert.equal(r.state.energy,s.energy);});
test('order progress and fulfillment consume exact requested tier once',()=>{let s=createInitialState();s=moveOrMerge(s,9,10).state;const order=s.currentOrders[0];assert.equal(countRequirement(s,order.requirements[0]),1);assert.equal(canFulfillOrder(s,order),true);const r=fulfillOrder(s,order.id);assert.equal(r.changed,true);assert.equal(r.state.stats.orders,1);assert.equal(r.state.coins,s.coins+order.rewards.coins);assert.equal(r.state.stars,s.stars+order.rewards.stars);assert.equal(countRequirement(r.state,order.requirements[0]),0);assert.equal(r.state.currentOrders.length,3);});
test('place upgrades cannot overspend stars',()=>{const s=createInitialState(),blocked=buildNextUpgrade(s);assert.equal(blocked.changed,false);assert.equal(blocked.reason,'not-enough-stars');const built=buildNextUpgrade({...s,stars:10});assert.equal(built.changed,true);assert.deepEqual(built.state.placeUpgrades,['lights']);assert.equal(built.state.stars,6);});
test('legacy or malformed saves reset safely to V2',()=>{const s=normalizeState({version:1,board:[]});assert.equal(s.version,2);assert.equal(s.board.length,BOARD_SIZE);});
test('max-tier items cannot merge further',()=>assert.equal(canMerge({kind:'item',family:'coffee',level:4},{kind:'item',family:'coffee',level:4}),false));
