import test from 'node:test';
import assert from 'node:assert/strict';
import { BOARD_SIZE, ITEM_FAMILIES, createInitialState, createOrder, makeItem, generateFromSlot, moveOrMerge, canMerge, countRequirement, canFulfillOrder, fulfillOrder, buildNextUpgrade, normalizeState, itemDefinition, unlockedFamilies, eligibleOrderTemplates, startNextPlace, nextPlaceId, activePlaceDefinition } from '../src/v2-game.js';

test('initial V2 board has two generators and merge-ready coffee/bakery pairs',()=>{const s=createInitialState();assert.equal(s.board.length,BOARD_SIZE);assert.equal(s.board.filter(i=>i?.kind==='generator').length,2);assert.equal(s.board.filter(i=>i?.family==='coffee'&&i.level===1).length,2);assert.equal(s.board.filter(i=>i?.family==='bakery'&&i.level===1).length,2);assert.equal(s.board.some(i=>i?.family==='sweet'),false);});
test('identical items merge into exactly one next-tier item',()=>{const s=createInitialState(),before=s.board.filter(Boolean).length,r=moveOrMerge(s,9,10);assert.equal(r.changed,true);assert.equal(r.type,'merge');assert.equal(r.item.family,'coffee');assert.equal(r.item.level,2);assert.equal(r.state.board[9],null);assert.equal(r.state.board.filter(Boolean).length,before-1);});
test('invalid merge preserves the board',()=>{const s=createInitialState(),snapshot=structuredClone(s.board),r=moveOrMerge(s,9,16);assert.equal(r.changed,false);assert.equal(r.reason,'not-mergeable');assert.deepEqual(r.state.board,snapshot);});
test('move to empty slot preserves identity',()=>{const s=createInitialState(),id=s.board[9].id,r=moveOrMerge(s,9,8);assert.equal(r.changed,true);assert.equal(r.type,'move');assert.equal(r.state.board[8].id,id);assert.equal(r.state.board[9],null);});
test('generator consumes one energy and spawns base item',()=>{const s=createInitialState(),r=generateFromSlot(s,0);assert.equal(r.changed,true);assert.equal(r.family,'coffee');assert.equal(r.state.energy,s.energy-1);assert.equal(r.state.board[r.spawnedIndex].level,1);});
test('full board blocks generation without energy loss',()=>{const s=createInitialState(),filler=s.board[9];s.board=s.board.map((slot,i)=>slot??{...filler,id:`fill-${i}`});const r=generateFromSlot(s,0);assert.equal(r.changed,false);assert.equal(r.reason,'board-full');assert.equal(r.state.energy,s.energy);});
test('order progress and fulfillment consume exact requested tier once',()=>{let s=createInitialState();s=moveOrMerge(s,9,10).state;const order=s.currentOrders[0];assert.equal(countRequirement(s,order.requirements[0]),1);assert.equal(canFulfillOrder(s,order),true);const r=fulfillOrder(s,order.id);assert.equal(r.changed,true);assert.equal(r.state.stats.orders,1);assert.equal(r.state.coins,s.coins+order.rewards.coins);assert.equal(r.state.stars,s.stars+order.rewards.stars);assert.equal(countRequirement(r.state,order.requirements[0]),0);assert.equal(r.state.currentOrders.length,3);});
test('place upgrades cannot overspend stars',()=>{const s=createInitialState(),blocked=buildNextUpgrade(s);assert.equal(blocked.changed,false);assert.equal(blocked.reason,'not-enough-stars');const built=buildNextUpgrade({...s,stars:10});assert.equal(built.changed,true);assert.deepEqual(built.state.placeUpgrades,['lights']);assert.equal(built.state.stars,6);});
test('legacy or malformed saves reset safely to V2',()=>{const s=normalizeState({version:1,board:[]});assert.equal(s.version,2);assert.equal(s.board.length,BOARD_SIZE);});
test('old valid saves gain progression fields without losing board',()=>{const old=createInitialState();delete old.currentPlace;delete old.completedPlaces;const before=structuredClone(old.board);const normalized=normalizeState(old);assert.equal(normalized.currentPlace,'coast');assert.deepEqual(normalized.completedPlaces,[]);assert.deepEqual(normalized.board,before);});
test('all core families expose six named art-backed tiers',()=>{for(const [family,def] of Object.entries(ITEM_FAMILIES)){assert.equal(def.stages.length,6,family);assert.equal(def.art.length,6,family);for(let level=1;level<=6;level+=1){const item=makeItem(family,level,`${family}-${level}`),resolved=itemDefinition(item);assert.equal(resolved.maxLevel,6);assert.equal(resolved.art,def.art[level-1]);assert.ok(resolved.name);}}});
test('tier five merges into premium tier six and tier six is terminal',()=>{const s=createInitialState();s.board[30]=makeItem('coffee',5,'coffee-five-a');s.board[31]=makeItem('coffee',5,'coffee-five-b');const r=moveOrMerge(s,30,31);assert.equal(r.changed,true);assert.equal(r.item.level,6);assert.equal(canMerge(r.item,{...r.item,id:'other'}),false);});
test('late raw order templates still use deeper production chains',()=>{const brunch=createOrder(7),finale=createOrder(9);assert.ok(brunch.requirements.some(req=>req.level>=4));assert.ok(finale.requirements.every(req=>req.level===6));assert.ok(finale.rewards.stars>brunch.rewards.stars);});

test('early pantry generation cannot create locked sweet items',()=>{let s=createInitialState();assert.deepEqual(unlockedFamilies(s),['coffee','bakery']);for(let n=0;n<3;n+=1){const r=generateFromSlot(s,6);assert.equal(r.changed,true);assert.equal(r.family,'bakery');s=r.state;}});
test('initial order pool never asks for locked sweet family',()=>{const s=createInitialState();assert.ok(s.currentOrders.every(order=>order.requirements.every(req=>req.family!=='sweet')));assert.ok(eligibleOrderTemplates(s).every(order=>order.requirements.every(req=>req.family!=='sweet')));});
test('building New Counter unlocks sweet production and sweet orders',()=>{let s={...createInitialState(),stars:50};s=buildNextUpgrade(s).state;const counter=buildNextUpgrade(s);assert.equal(counter.changed,true);assert.equal(counter.upgrade.id,'counter');assert.equal(counter.unlock.type,'family');assert.ok(unlockedFamilies(counter.state).includes('sweet'));let generated=counter.state;const first=generateFromSlot(generated,6);generated=first.state;const second=generateFromSlot(generated,6);assert.equal(second.family,'sweet');assert.ok(eligibleOrderTemplates(counter.state).some(order=>order.requirements.some(req=>req.family==='sweet')));});
test('Menu Wall unlocks advanced tier-four jobs',()=>{let s={...createInitialState(),stars:100};for(let i=0;i<3;i+=1)s=buildNextUpgrade(s).state;assert.ok(eligibleOrderTemplates(s).some(order=>order.requirements.some(req=>req.level===4)));});
test('Seating grants a real energy-capacity reward',()=>{let s={...createInitialState(),stars:100,energy:10};for(let i=0;i<3;i+=1)s=buildNextUpgrade(s).state;const seating=buildNextUpgrade(s);assert.equal(seating.upgrade.id,'seating');assert.equal(seating.unlock.type,'energy');assert.equal(seating.state.maxEnergy,50);assert.equal(seating.state.energy,20);});
test('Terrace unlocks premium late orders',()=>{let s={...createInitialState(),stars:100};for(let i=0;i<5;i+=1)s=buildNextUpgrade(s).state;assert.ok(eligibleOrderTemplates(s).some(order=>order.requirements.some(req=>req.level>=5)));});
test('finishing Café am Meer unlocks Place 02 without resetting the board',()=>{let s={...createInitialState(),stars:200};for(let i=0;i<6;i+=1)s=buildNextUpgrade(s).state;assert.ok(s.completedPlaces.includes('coast'));assert.equal(nextPlaceId(s),'harbor');const ids=s.board.filter(Boolean).map(item=>item.id);const next=startNextPlace(s);assert.equal(next.changed,true);assert.equal(next.state.currentPlace,'harbor');assert.equal(activePlaceDefinition(next.state).label,'Hafen-Pop-up');assert.deepEqual(next.state.placeUpgrades,[]);assert.deepEqual(next.state.board.filter(Boolean).map(item=>item.id),ids);assert.ok(next.state.currentOrders.every(order=>['Hafenstart','Steg-Kaffee','Marktpause'].includes(order.title)));});
test('Place 02 survives save normalization',()=>{let s={...createInitialState(),stars:200};for(let i=0;i<6;i+=1)s=buildNextUpgrade(s).state;s=startNextPlace(s).state;const restored=normalizeState(JSON.parse(JSON.stringify(s)));assert.equal(restored.currentPlace,'harbor');assert.ok(restored.completedPlaces.includes('coast'));assert.equal(activePlaceDefinition(restored).number,2);});
