import { webkit } from 'playwright';
import { mkdir, writeFile } from 'node:fs/promises';
const baseURL=process.env.QA_BASE_URL||'http://127.0.0.1:4173',outDir=process.env.QA_OUT_DIR||'qa-artifacts';await mkdir(outDir,{recursive:true});
const browser=await webkit.launch({headless:true});const context=await browser.newContext({viewport:{width:390,height:844},screen:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true,locale:'de-DE'});const page=await context.newPage();
const problems=[];page.on('console',m=>{if(['error','warning'].includes(m.type()))problems.push(`${m.type()}: ${m.text()}`)});page.on('pageerror',e=>problems.push(`pageerror: ${e.message}`));
const assert=(v,m)=>{if(!v)throw new Error(m)},shot=n=>page.screenshot({path:`${outDir}/${n}.png`,fullPage:false});
async function setUpgrades(ids){await page.evaluate(ids=>{const state=JSON.parse(localStorage.getItem('poply-v2-state-1'));state.placeUpgrades=ids;state.stars=999;localStorage.setItem('poply-v2-state-1',JSON.stringify(state));},ids);await page.reload({waitUntil:'networkidle'});await page.locator('.nav-tab[data-view="place"]').click();}
async function seed(){await page.goto(baseURL,{waitUntil:'networkidle'});await page.evaluate(async()=>{const game=await import('./src/v2-game.js');localStorage.setItem('poply-v2-state-1',JSON.stringify(game.createInitialState()));});await page.reload({waitUntil:'networkidle'});}
async function fit(label){const m=await page.evaluate(()=>{const hero=document.querySelector('.world-hero')?.getBoundingClientRect(),nav=document.querySelector('.main-nav')?.getBoundingClientRect();return {h:visualViewport?.height||innerHeight,hero:hero&&{top:hero.top,bottom:hero.bottom,left:hero.left,right:hero.right},nav:nav&&{top:nav.top,bottom:nav.bottom},scroll:document.documentElement.scrollHeight,inner:innerHeight};});assert(m.hero&&m.nav,`${label}: hero/nav missing`);assert(m.hero.bottom<=m.nav.top+1,`${label}: Place overlaps nav ${JSON.stringify(m)}`);assert(m.nav.bottom<=m.h+1,`${label}: nav clipped ${JSON.stringify(m)}`);assert(m.scroll<=m.inner+1,`${label}: document scrolls ${JSON.stringify(m)}`);return m;}
let report={},failure=null;
try{
  await seed();
  await setUpgrades(['lights','counter','menu','seating']);await page.waitForSelector('.place-coast .world-life-layer[data-life-stage="4"]');
  const coast=await page.evaluate(()=>{const hero=document.querySelector('.world-hero'),layer=document.querySelector('.world-life-layer'),gull=document.querySelector('.coast-gull'),steam=document.querySelector('.coast-table-cup .life-steam'),wave=document.querySelector('.place-coast .place-scene-svg path[stroke="#8dd8dc"]');if(!hero||!layer||!gull||!steam||!wave)return {missing:{hero:!hero,layer:!layer,gull:!gull,steam:!steam,wave:!wave}};const heroBox=hero.getBoundingClientRect(),layerBox=layer.getBoundingClientRect();return {hero:{w:heroBox.width,h:heroBox.height},layer:{w:layerBox.width,h:layerBox.height},gull:getComputedStyle(gull).animationName,steam:getComputedStyle(steam).animationName,wave:getComputedStyle(wave).animationName,cups:document.querySelectorAll('.coast-table-cup').length,patrons:document.querySelectorAll('.life-patron,.coast-guest,.sunset-guest').length};});
  assert(!coast.missing,`coast authored-life element missing ${JSON.stringify(coast)}`);assert(coast.cups===2,`coast seating should add two served tables ${JSON.stringify(coast)}`);assert(coast.patrons===0,`coast must not reintroduce placeholder people ${JSON.stringify(coast)}`);assert(coast.gull.includes('poply-gull-float'),`coast gull not alive ${JSON.stringify(coast)}`);assert(coast.steam.includes('poply-steam-rise'),`coast table steam not alive ${JSON.stringify(coast)}`);assert(coast.wave.includes('poply-life-wave'),`coast base water is static ${JSON.stringify(coast)}`);assert(Math.abs(coast.hero.w-coast.layer.w)<=3&&Math.abs(coast.hero.h-coast.layer.h)<=3,`coast life layer does not fit hero ${JSON.stringify(coast)}`);await fit('coast stage 4');await shot('80-coast-seating-comes-alive');

  await setUpgrades(['lights','counter','menu','seating','terrace','sign','sunset-lanterns','sunset-bar','sunset-lounge','sunset-fire','sunset-stage']);await page.waitForSelector('.place-sunset .world-life-layer[data-life-stage="5"]');
  const sunset=await page.evaluate(()=>{const note=document.querySelector('.sunset-note'),glass=document.querySelector('.sunset-table-glass .life-glass-shine'),wave=document.querySelector('.place-sunset .place-scene-svg path[stroke="#f5c492"]'),palms=document.querySelector('.sunset-palms'),fire=document.querySelector('.scene-upgrade.sunset-fire path');if(!note||!glass||!wave||!palms||!fire)return {missing:{note:!note,glass:!glass,wave:!wave,palms:!palms,fire:!fire}};return {glasses:document.querySelectorAll('.sunset-table-glass').length,notes:document.querySelectorAll('.sunset-note').length,patrons:document.querySelectorAll('.life-patron,.coast-guest,.sunset-guest').length,glassAnimation:getComputedStyle(glass).animationName,noteAnimation:getComputedStyle(note).animationName,waveAnimation:getComputedStyle(wave).animationName,palmAnimation:getComputedStyle(palms).animationName,fireAnimation:getComputedStyle(fire).animationName};});
  assert(!sunset.missing,`sunset authored-life element missing ${JSON.stringify(sunset)}`);assert(sunset.glasses===2,`sunset lounge should show two served drinks ${JSON.stringify(sunset)}`);assert(sunset.patrons===0,`sunset must not reintroduce placeholder people ${JSON.stringify(sunset)}`);assert(sunset.notes>=3,`sunset stage should emit authored music life ${JSON.stringify(sunset)}`);assert(sunset.glassAnimation.includes('poply-glass-shine'),`sunset drink glint static ${JSON.stringify(sunset)}`);assert(sunset.noteAnimation.includes('poply-note-rise'),`sunset notes static ${JSON.stringify(sunset)}`);assert(sunset.waveAnimation.includes('poply-life-wave'),`sunset water static ${JSON.stringify(sunset)}`);assert(sunset.palmAnimation.includes('poply-palm-sway'),`sunset palms static ${JSON.stringify(sunset)}`);assert(sunset.fireAnimation.includes('poply-fire-breathe'),`sunset fire static ${JSON.stringify(sunset)}`);await fit('sunset stage 5');await shot('81-sunset-stage-comes-alive');

  await setUpgrades(['lights','counter','menu','seating']);await page.setViewportSize({width:390,height:720});await fit('coast stage 4 short safari');await shot('82-coast-life-short-safari');
  report={coast,sunset};if(problems.length)throw new Error(`console problems: ${problems.join(' | ')}`);
}catch(e){failure=e;try{await shot('89-world-life-failure')}catch{}}
finally{await writeFile(`${outDir}/world-life-report.json`,JSON.stringify({report,problems,failure:failure?.message||null},null,2));await browser.close()}
if(failure)throw failure;console.log('World life WebKit QA passed.');
