import './aaa-order-choice-polish.js';
import './aaa-board-atmosphere.js';
import { ASSETS } from './aaa-view.js';
import { createUI } from './aaa-ui.js';
import { installDrag } from './aaa-drag.js';
import { installEnergyUI } from './aaa-energy-ui.js';
import { installPlayerUI } from './aaa-player-ui.js';
import { installDiscoveryUI } from './aaa-discovery-ui.js';
import { installStorageUI } from './aaa-storage-ui.js';
import { installFlowUI } from './aaa-flow-ui.js';
import { installServiceSpecialsUI } from './aaa-specials-ui.js';
import { installServiceCallUI } from './aaa-service-call-ui.js';
import { installServiceMomentsUI } from './aaa-service-moments-ui.js';
import { installPlacePowersUI } from './aaa-place-powers-ui.js';
import { installDailyUI } from './aaa-daily-ui.js';
import { installPlaceMapUI } from './aaa-place-map.js';
import { installPurposeUI } from './aaa-purpose-ui.js';
import { installLongTermUI } from './aaa-long-term-ui.js';
import { installPlaceScreenV3 } from './aaa-place-screen-v3.js';
import { installLayoutStability } from './aaa-layout-stability.js';
import { installGameplayFirst } from './aaa-gameplay-first.js';
import { installGuestUI } from './aaa-guest-ui.js';
import { installGuestDynamicsUI } from './aaa-guest-dynamics-ui.js';
import { installItemGuidance } from './aaa-item-guidance.js';
import { installBoardTradeUI } from './aaa-board-trade-ui.js';
import { installOrdersStageV2 } from './aaa-orders-stage-v2.js';
import { installOrderThemes } from './aaa-order-themes.js';
import { installWorldLife } from './aaa-world-life.js';
import { installPlaceLifeV2 } from './aaa-place-life-v2.js';
import { installGuestLife } from './aaa-guest-life-ui.js';
import { installAppUpdates } from './aaa-updates.js';

document.documentElement.style.setProperty('--poply-hero',`url(${ASSETS.hero})`);
document.documentElement.style.setProperty('--poply-atlas',`url(${ASSETS.atlas})`);
const root=document.querySelector('#app');
const toast=document.querySelector('#toast');
const ghost=document.querySelector('#drag-ghost');
const ui=createUI(root,toast);
installDrag({root,ghost,ui});
const syncViewport=()=>{
  const viewport=window.visualViewport;
  const height=viewport?viewport.height:window.innerHeight;
  document.documentElement.style.setProperty('--app-height',`${Math.round(height)}px`);
};
if(window.visualViewport)window.visualViewport.addEventListener('resize',syncViewport);
window.addEventListener('resize',syncViewport);
syncViewport();
ui.render();
installEnergyUI(root);
installPlayerUI(root);
installDiscoveryUI(root);
installStorageUI(root,ui);
installFlowUI(root);
installServiceSpecialsUI(root);
installServiceCallUI(root,ui);
installServiceMomentsUI(root);
installDailyUI(root,ui);
installPlaceMapUI(root);
installPurposeUI(root,ui);
installLongTermUI(root);
installPlaceScreenV3(root);
installPlacePowersUI(root,ui);
installGuestUI(root,ui);
installGuestDynamicsUI(root);
installWorldLife(root);
installPlaceLifeV2(root);
installGuestLife(root);
installLayoutStability(root);
installGameplayFirst(root);
installOrdersStageV2(root);
installOrderThemes(root);
installBoardTradeUI(root,ui);
installItemGuidance(root,ui);
installAppUpdates().catch(()=>{});