import { ITEM_FAMILIES, PLACE_UPGRADES, itemDefinition, countRequirement, canFulfillOrder, restorationStatus } from './v2-game.js';

const spriteStyle=sprite=>{const col=sprite%4,row=Math.floor(sprite/4);return `--sx:${col*33.333333}%;--sy:${row*33.333333}%`;};
const icon=id=>({lights:'✦',counter:'▰',menu:'☷',seating:'◫',terrace:'≈',sign:'P'})[id]||'✦';

export function createUi({copy,customers}){
  const itemArt=(item,size='normal')=>{const def=itemDefinition(item);return def?`<span class="item-art item-art--${size}" style="${spriteStyle(def.sprite)}" aria-hidden="true"></span>`:'';};
  const customer=order=>`<img class="customer-avatar" src="${customers[order.sequence%customers.length]}" alt="" aria-hidden="true">`;
  const requirements=(state,order,size='tiny')=>order.requirements.map(req=>{const sample={kind:'item',family:req.family,level:req.level},have=countRequirement(state,req);return `<span class="requirement ${have>=req.qty?'is-met':''}">${itemArt(sample,size)}<b>${have}/${req.qty}</b></span>`;}).join('');
  const status=state=>restorationStatus(state);
  const goal=(state,compact=false)=>{const s=status(state);if(s.complete)return `<div class="goal-card ${compact?'is-compact':''} is-complete"><div><span class="eyebrow">${copy.currentGoal}</span><strong>${copy.complete}</strong></div><span class="goal-check">✓</span></div>`;return `<div class="goal-card ${compact?'is-compact':''} ${s.missing===0?'is-ready':''}"><div class="goal-icon">${icon(s.upgrade.id)}</div><div class="goal-copy"><span class="eyebrow">${copy.currentGoal}</span><strong>${s.upgrade.label}</strong><div class="goal-progress"><span style="width:${Math.round(s.ratio*100)}%"></span></div><small>★ ${s.current}/${s.cost} · ${s.missing===0?copy.readyToBuild:copy.needStars(s.missing)}</small></div>${compact?'':`<button class="build-button" type="button" data-action="build" ${s.missing>0?'disabled':''}>${copy.build}</button>`}</div>`;};
  const resources=state=>`<div class="hud-resources"><span class="hud-pill"><i>⚡</i><b>${state.energy}/${state.maxEnergy}</b></span><span class="hud-pill"><i>●</i><b>${state.coins.toLocaleString()}</b></span><span class="hud-pill hud-stars"><i>★</i><b>${state.stars}</b></span></div>`;
  const header=state=>`<header class="top-hud"><button class="brand-button" type="button" data-view-target="board"><span>Poply</span><small>PLACES</small></button>${resources(state)}<button class="menu-button" type="button" data-action="menu" aria-label="${copy.menu}">☰</button></header>`;
  const nav=view=>`<nav class="bottom-nav" aria-label="Spielbereiche">${[['place','⌂',copy.place],['orders','☑',copy.orders],['board','▦',copy.board]].map(([key,symbol,label])=>`<button class="nav-button ${view===key?'is-active':''}" type="button" data-view-target="${key}" aria-pressed="${view===key}"><span>${symbol}</span><b>${label}</b></button>`).join('')}</nav>`;
  const menu=open=>open?`<div class="menu-backdrop" data-action="close-menu"><section class="menu-sheet" role="dialog" aria-modal="true" onclick="event.stopPropagation()"><div class="menu-head"><strong>Poply Places</strong><button type="button" data-action="close-menu">×</button></div><p>Premium Foundation · Café am Meer</p><button class="danger-button" type="button" data-action="reset">${copy.reset}</button></section></div>`:'';
  const miniOrder=(state,order)=>{const ready=canFulfillOrder(state,order);return `<button class="mini-order ${ready?'is-ready':''}" type="button" data-view-target="orders">${customer(order)}<span><strong>${order.title}</strong><span class="mini-needs">${requirements(state,order)}</span></span><i>${ready?'✓':'›'}</i></button>`;};
  const orderCard=(state,order)=>{const ready=canFulfillOrder(state,order);return `<article class="order-card ${ready?'is-ready':''}">${customer(order)}<div class="order-copy"><span class="order-status">${ready?copy.ready:copy.working}</span><strong>${order.title}</strong><div class="order-needs">${requirements(state,order,'medium')}</div></div><div class="order-footer"><div class="order-rewards"><span>● ${order.rewards.coins}</span><span>★ ${order.rewards.stars}</span><small>→ ${copy.place}</small></div><button class="deliver-button" type="button" data-order-id="${order.id}" ${ready?'':'disabled'}>${copy.deliver}</button></div></article>`;};
  const guidance=state=>{const needed=new Set(),counts=new Map();for(const order of state.currentOrders)for(const req of order.requirements)needed.add(`${req.family}:${req.level}`);for(const item of state.board)if(item?.kind==='item'&&item.level<ITEM_FAMILIES[item.family].stages.length){const key=`${item.family}:${item.level}`;counts.set(key,(counts.get(key)||0)+1);}return {needed,pairs:new Set([...counts].filter(([,n])=>n>=2).map(([key])=>key))};};
  const cell=(state,item,index,sets)=>{if(!item)return `<button class="board-cell is-empty" type="button" data-index="${index}" role="gridcell" aria-label="Empty"></button>`;const def=itemDefinition(item),gen=item.kind==='generator',key=gen?'':`${item.family}:${item.level}`,needed=!gen&&sets.needed.has(key),pair=!gen&&sets.pairs.has(key);return `<button class="board-cell has-item ${gen?'is-generator':''} ${needed?'is-needed':''} ${pair?'is-pair':''}" type="button" data-index="${index}" role="gridcell" aria-label="${def.name}">${itemArt(item)}${gen?'<span class="generator-mark">⚡</span>':`<span class="tier-badge">${item.level}</span>`}${needed?'<span class="need-mark">★</span>':''}</button>`;};
  const boardView=state=>{const sets=guidance(state),used=state.board.filter(Boolean).length;return `<section class="view view-board">${goal(state,true)}<div class="job-strip"><div class="strip-label"><strong>${copy.orders}</strong><small>${copy.jobsFund}</small></div><div class="job-strip-cards">${state.currentOrders.map(o=>miniOrder(state,o)).join('')}</div></div><div class="board-panel"><div class="board-title"><div><strong>${copy.boardTitle}</strong><small>${copy.boardRule}</small></div><span>${used}/49</span></div><div class="merge-board" role="grid">${state.board.map((item,index)=>cell(state,item,index,sets)).join('')}</div><div class="board-foot"><span>⚡ ${copy.tapGenerator}</span><button type="button" data-view-target="orders">${copy.orders} ›</button></div></div></section>`;};
  const ordersView=state=>{const s=status(state);return `<section class="view view-orders"><div class="orders-heading"><div><span class="eyebrow">${copy.jobsFund}</span><h1>${copy.orders}</h1><p>${copy.orderPurpose}</p></div><div class="star-meter"><span>★</span><strong>${s.complete?'✓':`${s.current}/${s.cost}`}</strong></div></div>${goal(state,true)}<div class="orders-list">${state.currentOrders.map(o=>orderCard(state,o)).join('')}</div></section>`;};
  const step=(state,item,index,s)=>{const done=state.placeUpgrades.includes(item.id),current=!done&&s.upgrade?.id===item.id;return `<div class="place-step ${done?'is-done':''} ${current?'is-current':''}"><span class="step-icon">${done?'✓':icon(item.id)}</span><div><small>${index+1}/${PLACE_UPGRADES.length}</small><strong>${item.label}</strong></div><span class="step-cost">${done?'✓':`★ ${item.cost}`}</span></div>`;};
  const placeView=state=>{const s=status(state);return `<section class="view view-place"><div class="place-stage" data-stage="${s.completed}"><div class="place-stage-shade"></div><div class="place-stage-copy"><span class="eyebrow">${copy.placeProgress} ${s.completed}/${s.total}</span><h1>Café am Meer</h1><p>${copy.placeIntro}</p></div></div><div class="place-content">${goal(state,false)}<div class="place-roadmap">${PLACE_UPGRADES.map((item,index)=>step(state,item,index,s)).join('')}</div>${s.upgrade?`<p class="upgrade-description">${s.upgrade.copy}</p>`:''}</div></section>`;};
  const current=(state,view)=>view==='place'?placeView(state):view==='orders'?ordersView(state):boardView(state);
  return {itemArt,header,nav,menu,current};
}
