import { ITEM_FAMILIES, createInitialState, normalizeState, itemDefinition, generateFromSlot, moveOrMerge, canFulfillOrder, countRequirement, fulfillOrder, buildNextUpgrade, nextPlaceUpgrade } from './v2-game.js';

const SAVE_KEY='poply-v2-state-1';
const de=(navigator.language||'').toLowerCase().startsWith('de');
const copy=de?{place:'Café am Meer',placeProgress:'Ausbau',finish:'Fertig',missing:'Noch nicht fertig',build:'Bauen',complete:'Place komplett',tapGenerator:'Tippe Generatoren an, ziehe zwei gleiche Items zusammen und erfülle Aufträge.',move:'Item verschoben',noMerge:'Nur zwei identische Items derselben Stufe können verschmelzen.',merged:'Merge!',spawned:'Neues Item erzeugt',boardFull:'Kein freier Platz. Merge zuerst ein paar Items.',noEnergy:'Keine Energie mehr.',orderDone:'Auftrag erledigt!',needStars:'Für den Ausbau fehlen noch Sterne.',built:'Ausbau geschafft!'}:{place:'Café by the Sea',placeProgress:'Build',finish:'Done',missing:'Not ready yet',build:'Build',complete:'Place complete',tapGenerator:'Tap generators, drag two identical items together and complete orders.',move:'Item moved',noMerge:'Only two identical items at the same tier can merge.',merged:'Merge!',spawned:'New item generated',boardFull:'No free slot. Merge some items first.',noEnergy:'No energy left.',orderDone:'Order complete!',needStars:'You need more stars for that upgrade.',built:'Upgrade complete!'};
const $=selector=>document.querySelector(selector);
const els={board:$('#merge-board'),orders:$('#orders'),energy:$('#energy-value'),coins:$('#coins-value'),stars:$('#stars-value'),placeName:$('#place-name'),placeProgress:$('#place-progress'),placeProgressFill:$('#place-progress-fill'),upgradeName:$('#upgrade-name'),upgradeCost:$('#upgrade-cost'),buildButton:$('#build-button'),hero:$('#place-hero'),toast:$('#toast'),hint:$('#hint'),itemInfo:$('#item-info'),reset:$('#reset-button')};
let state=loadState(); let drag=null; let toastTimer=0;
function loadState(){try{const raw=localStorage.getItem(SAVE_KEY);return raw?normalizeState(JSON.parse(raw)):createInitialState();}catch{return createInitialState();}}
function saveState(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(state));}catch{}}
function vibrate(pattern){try{navigator.vibrate?.(pattern);}catch{}}
function showToast(message,tone='good'){clearTimeout(toastTimer);els.toast.textContent=message;els.toast.dataset.tone=tone;els.toast.classList.add('show');toastTimer=setTimeout(()=>els.toast.classList.remove('show'),1200);}
const spriteClass=sprite=>`sprite-${sprite}`;
function itemMarkup(item,compact=false){const def=itemDefinition(item);return def?`<span class="item-art ${spriteClass(def.sprite)}${compact?' compact':''}" aria-hidden="true"></span>`:'';}
const itemLabel=item=>itemDefinition(item)?.name??'';
function renderResources(){els.energy.textContent=`${state.energy}/${state.maxEnergy}`;els.coins.textContent=state.coins.toLocaleString(de?'de-DE':'en-US');els.stars.textContent=state.stars.toLocaleString(de?'de-DE':'en-US');}
function renderPlace(){const done=state.placeUpgrades.length;els.placeName.textContent=copy.place;els.placeProgress.textContent=`${copy.placeProgress} ${done}/3`;els.placeProgressFill.style.width=`${done/3*100}%`;els.hero.dataset.stage=String(done);const next=nextPlaceUpgrade(state);if(!next){els.upgradeName.textContent=copy.complete;els.upgradeCost.textContent='★';els.buildButton.textContent='✓';els.buildButton.disabled=true;return;}els.upgradeName.textContent=next.label;els.upgradeCost.textContent=`★ ${next.cost}`;els.buildButton.textContent=copy.build;els.buildButton.disabled=state.stars<next.cost;}
function renderOrders(){els.orders.innerHTML=state.currentOrders.map(order=>{const ready=canFulfillOrder(state,order);const requirements=order.requirements.map(req=>{const sample={kind:'item',family:req.family,level:req.level};const have=countRequirement(state,req);return `<div class="order-need ${have>=req.qty?'met':''}">${itemMarkup(sample,true)}<span>${have}/${req.qty}</span></div>`;}).join('');return `<article class="order-card ${ready?'ready':''}"><div class="customer-orb" aria-hidden="true">${order.sequence%3===0?'☺':order.sequence%3===1?'★':'♥'}</div><div class="order-main"><strong>${order.title}</strong><div class="order-needs">${requirements}</div></div><div class="order-reward"><span>● ${order.rewards.coins}</span><span>★ ${order.rewards.stars}</span></div><button class="order-button" data-order="${order.id}" ${ready?'':'disabled'}>${copy.finish}</button></article>`;}).join('');els.orders.querySelectorAll('.order-button').forEach(button=>button.addEventListener('click',()=>{const result=fulfillOrder(state,button.dataset.order);if(!result.changed){showToast(copy.missing,'bad');return;}state=result.state;saveState();vibrate([12,20,12]);showToast(`${copy.orderDone} +${result.rewards.coins} ●  +${result.rewards.stars} ★`);render();}));}
function renderBoard(){els.board.innerHTML=state.board.map((item,index)=>{if(!item)return `<button class="merge-cell empty" data-index="${index}" aria-label="Empty slot"></button>`;const def=itemDefinition(item);const generator=item.kind==='generator';return `<button class="merge-cell has-item ${generator?'generator':''}" data-index="${index}" aria-label="${def.name}">${itemMarkup(item)}${generator?'':`<span class="tier">${item.level}</span>`}${generator?'<span class="generator-bolt">⚡</span>':''}</button>`;}).join('');els.board.querySelectorAll('.merge-cell.has-item').forEach(cell=>{cell.addEventListener('pointerdown',onPointerDown);cell.addEventListener('click',onCellClick);});}
function onCellClick(event){const index=Number(event.currentTarget.dataset.index);const item=state.board[index];if(!item)return;els.itemInfo.innerHTML=`${itemMarkup(item,true)}<span><strong>${itemLabel(item)}</strong>${item.kind==='item'?`<small>${ITEM_FAMILIES[item.family].label} · Stufe ${item.level}</small>`:'<small>Generator · antippen</small>'}</span>`;}
function onPointerDown(event){const index=Number(event.currentTarget.dataset.index);drag={index,x:event.clientX,y:event.clientY,moved:false,pointerId:event.pointerId};event.currentTarget.setPointerCapture?.(event.pointerId);event.currentTarget.classList.add('dragging');}
function onPointerMove(event){if(!drag||event.pointerId!==drag.pointerId)return;if(Math.hypot(event.clientX-drag.x,event.clientY-drag.y)>8)drag.moved=true;const target=document.elementFromPoint(event.clientX,event.clientY)?.closest?.('.merge-cell');els.board.querySelectorAll('.drop-target').forEach(cell=>cell.classList.remove('drop-target'));if(target&&Number(target.dataset.index)!==drag.index)target.classList.add('drop-target');}
function onPointerUp(event){if(!drag||event.pointerId!==drag.pointerId)return;const from=drag.index,source=state.board[from],targetEl=document.elementFromPoint(event.clientX,event.clientY)?.closest?.('.merge-cell');els.board.querySelectorAll('.dragging,.drop-target').forEach(cell=>cell.classList.remove('dragging','drop-target'));if(!drag.moved&&source?.kind==='generator'){const result=generateFromSlot(state,from);if(!result.changed)showToast(result.reason==='board-full'?copy.boardFull:result.reason==='no-energy'?copy.noEnergy:copy.noMerge,'bad');else{state=result.state;saveState();vibrate(8);showToast(copy.spawned);render();}drag=null;return;}if(targetEl){const to=Number(targetEl.dataset.index),result=moveOrMerge(state,from,to);if(result.changed){state=result.state;saveState();if(result.type==='merge'){vibrate([10,12,16]);showToast(`${copy.merged} ${itemLabel(result.item)}`);}else showToast(copy.move);render();}else if(to!==from)showToast(copy.noMerge,'bad');}drag=null;}
function render(){renderResources();renderPlace();renderOrders();renderBoard();els.hint.textContent=copy.tapGenerator;}
els.buildButton.addEventListener('click',()=>{const result=buildNextUpgrade(state);if(!result.changed){showToast(copy.needStars,'bad');return;}state=result.state;saveState();vibrate([18,25,18,25,24]);showToast(`${copy.built} ${result.upgrade.label}`);render();});
els.reset.addEventListener('click',()=>{state=createInitialState();saveState();render();showToast(copy.tapGenerator);});
window.addEventListener('pointermove',onPointerMove,{passive:true});window.addEventListener('pointerup',onPointerUp);window.addEventListener('pointercancel',()=>{drag=null;els.board.querySelectorAll('.dragging,.drop-target').forEach(cell=>cell.classList.remove('dragging','drop-target'));});
render();
